from __future__ import annotations


def generate_paper_trading_report(
    *,
    order_count: int,
    submitted_count: int,
    filled_count: int,
    trade_count: int,
    risk_breach_count: int,
    final_cash: float,
    final_equity: float,
    kill_switch: bool,
) -> str:
    return "\n".join(
        [
            "# Phase 5 Paper Trading Report",
            "",
            "## Scope",
            "",
            "This report is generated by the local paper trading simulator. It does not "
            "connect to a real broker and does not place real orders.",
            "",
            "## Safety",
            "",
            f"- Kill switch enabled: {kill_switch}",
            "- Every order is checked by the risk engine before broker submission.",
            "- Rejected orders are not submitted to the paper broker.",
            "",
            "## Summary",
            "",
            f"- Orders: {order_count}",
            f"- Submitted orders: {submitted_count}",
            f"- Filled orders: {filled_count}",
            f"- Trades: {trade_count}",
            f"- Risk breaches: {risk_breach_count}",
            f"- Final cash: {final_cash:.2f}",
            f"- Final equity: {final_equity:.2f}",
            "",
            "## Lifecycle",
            "",
            "- created",
            "- submitted",
            "- partially_filled",
            "- filled",
            "- cancelled",
            "- rejected",
            "",
        ]
    )
