import json
from pathlib import Path

from quant_system.api.server import create_app

GENERATED_TYPES = Path("src/frontend/lib/api.generated.ts")
PACKAGE_JSON = Path("src/frontend/package.json")
TYPEGEN_SCRIPT = Path("src/frontend/scripts/generate-api-types.mjs")
LEDGER = Path("docs/audits/remediation_ledger_2026-06-23.md")


def test_openapi_type_generation_uses_uv_ai_quant_environment() -> None:
    script = TYPEGEN_SCRIPT.read_text(encoding="utf-8")

    assert "UV_CACHE_DIR" in script
    assert "UV_PROJECT_ENVIRONMENT" in script
    assert "ai-quant" in script
    assert ".tmp" in script
    assert "...process.env" in script


def test_frontend_declares_openapi_type_generation_contract(tmp_path) -> None:
    package = json.loads(PACKAGE_JSON.read_text(encoding="utf-8"))

    assert package["scripts"]["generate:api-types"] == "node scripts/generate-api-types.mjs"
    assert "openapi-typescript" in package["devDependencies"]

    generated = GENERATED_TYPES.read_text(encoding="utf-8")
    assert "This file was auto-generated by openapi-typescript" in generated
    assert "export interface components" in generated

    schemas = create_app(output_dir=tmp_path).openapi()["components"]["schemas"]
    for schema_name in (
        "BacktestRunResponse",
        "PaperRunResponse",
        "RecentRunsResponse",
        "PredictionMarketTimeseriesBacktestResultResponse",
    ):
        assert schema_name in schemas
        assert f"{schema_name}:" in generated


def test_remediation_ledger_records_openapi_generation_scope() -> None:
    ledger = LEDGER.read_text(encoding="utf-8")

    for required in (
        "Package B status: initial generation contract established",
        "`src/frontend/lib/api.generated.ts` is generated from FastAPI OpenAPI schema",
        "FileResponse artifact download routes are explicit OpenAPI response-model exemptions",
        "Existing `apiGet` / `apiPost` client behavior remains hand-maintained",
    ):
        assert required in ledger
