import Link from "next/link";
import { ShieldAlert } from "lucide-react";
import { DataPreviewTable } from "@/components/DataPreviewTable";
import { DataSourceBadge } from "@/components/DataSourceBadge";
import { ErrorBanner } from "@/components/ErrorBanner";
import { formatMoney, getHealth, getPaperRunDetail } from "@/lib/api";

type PaperRunDetailPageProps = {
  params?: Promise<{ runId?: string }>;
};

export default async function PaperRunDetailPage({ params }: PaperRunDetailPageProps) {
  const runId = (await params)?.runId ?? "";
  const [health, detail] = await Promise.all([getHealth(), getPaperRunDetail(runId)]);
  const metadata = detail.metadata ?? {};
  const source = typeof metadata.source === "string" ? metadata.source : undefined;

  return (
    <main className="h-full overflow-y-auto bg-bg-base p-5">
      <ErrorBanner messages={[health.apiError, detail.apiError]} />
      <header className="mb-5 flex flex-wrap items-start justify-between gap-4 border-b border-border-subtle pb-4">
        <div>
          <p className="font-label-caps uppercase text-text-secondary">Paper Trading</p>
          <h1 className="mt-1 font-headline-xl text-text-primary">Paper Run Detail</h1>
          <p className="mt-1 font-data-mono text-text-secondary">{runId}</p>
          {source ? (
            <div className="mt-3">
              <DataSourceBadge source={source} />
            </div>
          ) : null}
        </div>
        <Link className="rounded border border-border-subtle px-3 py-2 font-body-sm text-text-primary" href="/paper-trading">
          Back to Paper Trading
        </Link>
      </header>

      <section className="mb-4 grid gap-3 md:grid-cols-4">
        <Metric label="Final Equity" value={formatMoney(toNumber(metadata.final_equity))} />
        <Metric label="Orders" value={String(metadata.order_count ?? detail.orders.length)} />
        <Metric label="Trades" value={String(metadata.trade_count ?? detail.trades.length)} />
        <Metric label="Risk Breaches" value={String(metadata.risk_breach_count ?? detail.risk_breaches.length)} danger />
      </section>

      <section className="mb-4 flex items-center gap-2 rounded border border-warning/40 bg-warning/10 p-3 font-body-sm text-warning">
        <ShieldAlert size={18} />
        Paper-only simulation. Live trading is disabled and this page cannot submit orders.
      </section>

      <section className="grid gap-4 lg:grid-cols-2">
        <DataPreviewTable
          description="Orders generated by this paper run."
          emptyDescription="No order rows were saved for this run."
          emptyTitle="Orders"
          rows={detail.orders}
          title="Orders"
        />
        <DataPreviewTable
          description="Order status events generated by this paper run."
          emptyDescription="No order lifecycle rows were saved for this run."
          emptyTitle="Order Lifecycle"
          rows={detail.order_events}
          title="Order Lifecycle"
        />
        <DataPreviewTable
          description="Trades simulated by this paper run."
          emptyDescription="No trade rows were saved for this run."
          emptyTitle="Trades"
          rows={detail.trades}
          title="Trades"
        />
        <DataPreviewTable
          description="Risk checks triggered during this paper run."
          emptyDescription="No risk breach rows were saved for this run."
          emptyTitle="Risk Breaches"
          rows={detail.risk_breaches}
          title="Risk Breaches"
        />
        <div className="lg:col-span-2">
          <DataPreviewTable
            description="Run request and saved output paths."
            emptyDescription="Metadata is empty for this run."
            emptyTitle="Metadata unavailable"
            rows={objectRows(metadata)}
            title="Metadata"
          />
        </div>
      </section>
    </main>
  );
}

function Metric({
  label,
  value,
  danger = false,
}: {
  label: string;
  value: string;
  danger?: boolean;
}) {
  return (
    <div className="rounded border border-border-subtle bg-bg-surface p-3">
      <div className="font-label-caps text-text-secondary">{label}</div>
      <div className={`mt-2 font-data-mono text-lg font-bold ${danger ? "text-danger" : "text-text-primary"}`}>
        {value}
      </div>
    </div>
  );
}

function objectRows(value: unknown) {
  if (typeof value !== "object" || value === null) {
    return [];
  }
  return Object.entries(value as Record<string, unknown>).map(([key, item]) => ({
    key,
    value: typeof item === "object" && item !== null ? JSON.stringify(item) : item,
  }));
}

function toNumber(value: unknown) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : undefined;
}
