import Link from "next/link";
import { ShieldAlert } from "lucide-react";
import { DataPreviewTable } from "@/components/DataPreviewTable";
import { DataSourceBadge } from "@/components/DataSourceBadge";
import { ErrorBanner } from "@/components/ErrorBanner";
import { formatMoney, getPaperRunDetail } from "@/lib/api";
import { localizePath } from "@/lib/locale";
import { getCachedHealth } from "@/lib/serverApi";
import { getServerLocale } from "@/lib/serverLocale";

const copy = {
  en: {
    eyebrow: "Paper Trading",
    title: "Paper Run Detail",
    back: "Back to Paper Trading",
    finalEquity: "Final Equity",
    orders: "Orders",
    trades: "Trades",
    riskBreaches: "Risk Breaches",
    safety: "Paper-only simulation. Live trading is disabled and this page cannot submit orders.",
    ordersDesc: "Orders generated by this paper run.",
    ordersEmpty: "No order rows were saved for this run.",
    lifecycle: "Order Lifecycle",
    lifecycleDesc: "Order status events generated by this paper run.",
    lifecycleEmpty: "No order lifecycle rows were saved for this run.",
    tradesDesc: "Trades simulated by this paper run.",
    tradesEmpty: "No trade rows were saved for this run.",
    riskDesc: "Risk checks triggered during this paper run.",
    riskEmpty: "No risk breach rows were saved for this run.",
    metadata: "Metadata",
    metadataDesc: "Run request and saved output paths.",
    metadataEmptyTitle: "Metadata unavailable",
    metadataEmpty: "Metadata is empty for this run.",
  },
  zh: {
    eyebrow: "模拟交易",
    title: "模拟运行明细",
    back: "返回模拟交易",
    finalEquity: "期末权益",
    orders: "订单",
    trades: "成交",
    riskBreaches: "风控触发",
    safety: "仅模拟运行。实盘交易已禁用,本页面无法提交任何订单。",
    ordersDesc: "本次模拟运行生成的订单。",
    ordersEmpty: "该运行没有保存订单记录。",
    lifecycle: "订单生命周期",
    lifecycleDesc: "本次模拟运行生成的订单状态事件。",
    lifecycleEmpty: "该运行没有保存订单生命周期记录。",
    tradesDesc: "本次模拟运行撮合的成交。",
    tradesEmpty: "该运行没有保存成交记录。",
    riskDesc: "本次模拟运行触发的风控检查。",
    riskEmpty: "该运行没有保存风控触发记录。",
    metadata: "元数据",
    metadataDesc: "运行请求参数与输出文件路径。",
    metadataEmptyTitle: "元数据不可用",
    metadataEmpty: "该运行的元数据为空。",
  },
} as const;

type PaperRunDetailPageProps = {
  params?: Promise<{ runId?: string }>;
};

export default async function PaperRunDetailPage({ params }: PaperRunDetailPageProps) {
  const locale = await getServerLocale();
  const text = copy[locale];
  const runId = (await params)?.runId ?? "";
  const [health, detail] = await Promise.all([getCachedHealth(), getPaperRunDetail(runId)]);
  const metadata = detail.metadata ?? {};
  const source = typeof metadata.source === "string" ? metadata.source : undefined;

  return (
    <main className="h-full overflow-y-auto bg-bg-base p-5">
      <ErrorBanner messages={[health.apiError, detail.apiError]} />
      <header className="mb-5 flex flex-wrap items-start justify-between gap-4 border-b border-border-subtle pb-4">
        <div>
          <p className="font-label-caps uppercase text-text-secondary">{text.eyebrow}</p>
          <h1 className="mt-1 font-headline-xl text-text-primary">{text.title}</h1>
          <p className="mt-1 font-data-mono text-text-secondary">{runId}</p>
          {source ? (
            <div className="mt-3">
              <DataSourceBadge source={source} />
            </div>
          ) : null}
        </div>
        <Link
          className="rounded-lg border border-border-subtle px-3 py-2 font-body-sm text-text-primary transition-colors hover:bg-bg-surface-muted"
          href={localizePath("/paper-trading", locale)}
        >
          {text.back}
        </Link>
      </header>

      <section className="mb-4 grid gap-3 md:grid-cols-4">
        <Metric label={text.finalEquity} value={formatMoney(toNumber(metadata.final_equity))} />
        <Metric label={text.orders} value={String(metadata.order_count ?? detail.orders.length)} />
        <Metric label={text.trades} value={String(metadata.trade_count ?? detail.trades.length)} />
        <Metric label={text.riskBreaches} value={String(metadata.risk_breach_count ?? detail.risk_breaches.length)} danger />
      </section>

      <section className="mb-4 flex items-center gap-2 rounded-lg border border-warning/40 bg-warning/10 p-3 font-body-sm text-warning">
        <ShieldAlert size={18} />
        {text.safety}
      </section>

      <section className="grid gap-4 lg:grid-cols-2">
        <DataPreviewTable
          description={text.ordersDesc}
          emptyDescription={text.ordersEmpty}
          emptyTitle={text.orders}
          rows={detail.orders}
          title={text.orders}
        />
        <DataPreviewTable
          description={text.lifecycleDesc}
          emptyDescription={text.lifecycleEmpty}
          emptyTitle={text.lifecycle}
          rows={detail.order_events}
          title={text.lifecycle}
        />
        <DataPreviewTable
          description={text.tradesDesc}
          emptyDescription={text.tradesEmpty}
          emptyTitle={text.trades}
          rows={detail.trades}
          title={text.trades}
        />
        <DataPreviewTable
          description={text.riskDesc}
          emptyDescription={text.riskEmpty}
          emptyTitle={text.riskBreaches}
          rows={detail.risk_breaches}
          title={text.riskBreaches}
        />
        <div className="lg:col-span-2">
          <DataPreviewTable
            description={text.metadataDesc}
            emptyDescription={text.metadataEmpty}
            emptyTitle={text.metadataEmptyTitle}
            rows={objectRows(metadata)}
            title={text.metadata}
          />
        </div>
      </section>
    </main>
  );
}

function Metric({
  label,
  value,
  danger = false,
}: {
  label: string;
  value: string;
  danger?: boolean;
}) {
  return (
    <div className="rounded-lg border border-border-subtle bg-bg-surface p-3">
      <div className="font-label-caps text-text-secondary">{label}</div>
      <div className={`mt-2 font-data-mono text-lg font-bold ${danger ? "text-danger" : "text-text-primary"}`}>
        {value}
      </div>
    </div>
  );
}

function objectRows(value: unknown) {
  if (typeof value !== "object" || value === null) {
    return [];
  }
  return Object.entries(value as Record<string, unknown>).map(([key, item]) => ({
    key,
    value: typeof item === "object" && item !== null ? JSON.stringify(item) : item,
  }));
}

function toNumber(value: unknown) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : undefined;
}
